### PR TITLE
Use latest decode_raw

### PR DESCRIPTION
**Pull request by webmaster128**
- Use latest decode_raw
- Handle None case of `try_parse_entries` properly (this is broken protobuf, not an empty list)

### CODE REVIEW

**Comment by konsumer** [comment]
I added code for error-handling, and this strips that. Is this better than console_error_panic_hook? I like that console_error_panic_hook shows a stack and helpful info about where the error was. Does this do that?

Screen Shot 2022-02-11 at 4 15 00 AM

**Comment by webmaster128** [comment]
This PR does not change the error handling. `console_error_panic_hook` is still used to convert errors to console logs.

What is happening here is that the `None` case of `try_parse_entries` is not converted to an empty list anymore. This is what `.unwrap_or_default()` does (the empty vector is the default value of a vector). I added this call before. However, this was a mistake because `None` does not mean no entries, it means the bytes cannot be parsed correctly as protobuf.

**Comment by konsumer** [comment]
> This PR does not change the error handling. 

It does as far as I can tell. You need to call `console_error_panic_hook::set_once()` to trigger error-handling, so I did that in `parse_raw`, which is removed in this PR. It doesn't matter, I can just add it back, if it doesn't go into merge. I have seen what you are talking about (bad binary will just return an empty array, in JS side)and I see what you are doing here. Looks good. Merging.

**Comment by konsumer** [comment]
oh, yep, it's still there after merge.

**Pull request merged**
